@base = http://localhost:3333/users


###
GET {{ base }}

###
POST {{ base }}
content-type: application/json

{
    "name": "Fulano de Tal",
    "email": "falano1@google.com",
    "password": "1234"
}
