@base = http://localhost:3333


###
GET {{ base }}/users

### Cadastro
POST {{ base }}/users
content-type: application/json

{
  "name": "fulano22",
  "email": "falano22@google.com",
  "password": "1234"
}

### Login
POST {{ base }}/sessions
content-type: application/json

{
  "email": "falano2@google.com",
  "password": "1234567"
}

### Update
PUT {{ base }}/users
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNTk3MjgzMjY3LCJleHAiOjE1OTc4ODgwNjd9.6-OuiqVC5Vc3YqeboMr8_WHfouCilV92i482o9pABxo

{
  "name": "falono2",
  "email": "falano2@google.com",
  "oldPassword": "12345678",
  "password": "1234567",
  "confirmPassword": "1234567"
}


###
GET http://serviceviusat.dwnewsoftware.com/api/usuario/Categorias

###
GET https://brasilapi.com.br/api/cep/v1/05010000
